<number> ::= ("0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9")
<date> ::= <number> + "-" <number> + "-" <number> + <sp> <number> + ":" <number> + ":" <number> + "," <number> +
<level> ::= ("DEBUG"|"INFO"|"WARN"|"ERROR"|"FATAL")
<package> ::= <notsp>
<thread> ::= <notsp>
<command> ::= ("add"|"remove"|"set")
<global> ::= ("globalAdd"|"globalRemove")
<move> ::= "move"
<name> ::= ("A"|"B"|"C") ("A"|"B"|"C") ("A"|"B"|"C")
<name1> ::= <name>
<name2> ::= <name>
<point> ::= <number> + "." <number> +
<basiccommand> ::= <date> <sp> <level> <sp> <package> <sp> <thread> <sp> <command> <sp> <name1> ":" <point>
<globalcommand> ::= <date> <sp> <level> <sp> <package> <sp> <thread> <sp> <global> <sp> <point>
<movecommand> ::= <date> <sp> <level> <sp> <package> <sp> <thread> <sp> <move> <sp> "from" <sp> <name1> <sp> "to" <sp> <name2> <sp> ":" <sp> <point>
<root> ::= <basiccommand> | <globalcommand> | <movecommand>
